#!/usr/bin/env python3

import os
import subprocess

with open('params.pickle', 'rb') as f:
  import pickle
  params = pickle.load(f)

subprocess.check_call(
  ['openssl', 'dhparam', '-out', 'server/dh2048.pem', '2048'])

with open('server/server.cnf', 'w') as f:
  print('''\
# This configuration file is used by the 'req' command when the server certificate is created.
[ req ]
default_bits            = 2048
default_md              = sha1
encrypt_key             = no
prompt                  = no
string_mask             = utf8only
distinguished_name      = server_distinguished_name
req_extensions          = req_cert_extensions
# attributes              = req_attributes

[ server_distinguished_name ]
countryName             = %(country)s
localityName            = %(locality)s
organizationName        = %(organization)s
commonName              = %(commonName)s
emailAddress            = %(email)s

[ req_cert_extensions ]
nsCertType              = server
subjectAltName          = email:%(email)s
''' % params, file = f)

subprocess.check_call(
  ['openssl', 'req', '-new', '-config', 'server/server.cnf',
   '-keyout', 'server/server.key', '-out', 'server/server.req'])
os.chmod('server/server.key', 0o400)
subprocess.check_call(
  ['openssl', 'ca', '-config', 'ca/ca-sign.cnf',
   '-extensions', 'X509_server',
   '-in', 'server/server.req', '-out', 'server/server.crt'])
